// svelte-tutorial/src/lib/Hero.svelte
<script>
    const { name, percentage, data } = $props();
</script>

<section id="hero">
    <h3 class='text-large'>
        {name}, you have {data["weeks"]} weeks left. Make them count 🫡
    </h3>
    <div class='btns-container'>
        <button>Not {name}?</button>
        <button class='link-button'>Copy link</button>
        <button class='link-button'>Reset data</button>
    </div>
    <div class='progress-bar'>
        <div>
            <div>
                <i class='fa-solid fa-baby'></i>
                <h6 class='bar-label'>Birth</h6>
            </div>
            <h6>{65}%</h6>
        </div>
        <div>
            <h6 class='bar-label'>Death</h6>
            <i class='fa-solid fa-skull'></i>
        </div>
    </div>
</section>

// reactjs-tutorial/src/components/Hero.jsx

export default function Hero(props) {
  const { name, lifeExpectancy, data, percentage } = props

  return (
    <section id="hero">
      <h3 className='text-large'>
        {name}, you have {data.weeks} weeks left. Make them count 🫡
      </h3>
      <div className='btns-container'>
        <button>Not {name}?</button>
        <button className='link-button'>Copy link</button>
        <button className='link-button'>Reset data</button>
      </div>
      <div className='progress-bar'>
        <div>
          <div>
            <i className='fa-solid fa-baby' />
            <h6 className='bar-label'>Birth</h6>
          </div>
          <h6>{percentage}</h6>
        </div>
        <div>
        <div>
            <i className='fa-solid fa-skull' />
            <h6 className='bar-label'>Death</h6>
          </div>
        </div>
      </div>
    </section>
  )
}
