// vue-tutorial/src/components/Portal.vue
<script setup>
    defineProps({
        showModal: Boolean,
        handleCloseModal: Function
    })
</script>

<template>
    <Teleport v-if="showModal" to="#portal">
        <div class="portal-container">
            <div class="portal-underlay" role="button" tabindex="0" @click="handleCloseModal"></div>
            <div class="portal-content">
                <slot />
            </div>
        </div>
    </Teleport>
</template>

<style scoped>

</style>

// reactjs-tutorial/src/components/Portal.jsx
import ReactDom from 'react-dom'

export default function Portal(props) {
  const { handleCloseModal, children } = props

  return ReactDom.createPortal(
    <div className='portal-container'>
      <div onClick={handleCloseModal} className='portal-underlay'></div>
      <div className='portal-content'>
        {children}
      </div>
    </div>,
    document.getElementById('portal')
  )
}
