// reactjs-tutorial/src/components/Form.jsx
export default function Form(props) {
  const { handleCloseModal, handleUpdateData } = props

  const days = Array.from({ length: 31 }, (_, i) => i + 1)
  const months = [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
  ]
  const years = Array.from({ length: 100 }, (_, i) => new Date().getFullYear() - i)

  return (
    <section id="form">
      <div>
        <h4 className='text-gradient'>Your Details</h4>
        <button onClick={handleCloseModal} className='link-button'>
          <i className='fa-solid fa-xmark' />
        </button>
      </div>
      <div>
        <label>Name</label>
        <input type='text' required />
      </div>
      <div>
        <label>Birthday</label>
        <div className='bday'>
          <select>
            {days.map((d) => {
              return (
                <option key={d} value={d}>{d}</option>
              )
            })}
          </select>
          <select>
            {months.map((m, i) => {
              return (
                <option key={i} value={i + 1}>{m}</option>
              )
            })}
          </select>
          <select>
            {years.map((y) => {
              return (
                <option key={y} value={y}>{y}</option>
              )
            })}
          </select>
        </div>
      </div>
      <div>
        <label>Life expectancy (years)</label>
        <input type='number' max={120} required />
      </div>
      <button onClick={() => {}}>
        Save
      </button>
    </section>
  )
}

// vue-tutorial/src/components/Form.vue
<script setup>
    import { ref } from 'vue'

    const { handleCloseModal, handleUpdateData } = defineProps({
        handleCloseModal: Function,
        handleUpdateData: Function
    })

    const name = ref('')

    const currYear = new Date().getFullYear()
    const day = ref(1)
    const month = ref(1)
    const year = ref(currYear)

    const lifeExpectancy = ref(80)

    // Options
    const days = Array.from({ length: 31 }, (_, i) => i + 1)
    const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ]
    const years = Array.from({ length: 100 }, (_, i) => currYear - i)

    function handleSave() {
        handleUpdateData(name.value, `${year.value}-${month.value}-${day.value}`, lifeExpectancy.value)
    }
</script>

<template>
    <section id="form">
        <div>
            <h4 class="text-gradient">Your Details</h4>
            <button @click="handleCloseModal" class="link-button">
                <i class="fa-solid fa-xmark"></i>
            </button>
        </div>
        <div>
            <label for="name">Name</label>
            <input v-model="name" type="text" id="name" required />
        </div>
        <div>
            <div>
                Birthday
            </div>
            <div class="bday">
                <select v-model="day">
                    <option v-for="d in days" :key="d" :value="d">
                        {{ d }}
                    </option>
                </select>
                <select v-model="month">
                    <option v-for="(m, index) in months" :key="index" :value="index + 1">
                        {{ m }}
                    </option>
                </select>
                <select v-model="year">
                    <option v-for="y in years" :key="y" :value="y">
                        {{ y }}
                    </option>
                </select>
            </div>
        </div>
        <div>
            <label for="lifeExpectancy">Life Expectancy (years)</label>
            <input id="lifeExpectancy" type="number" max="120" required v-model="lifeExpectancy" />
        </div>

        <button @click="handleSave">Save</button>
    </section>
</template>

<style scoped>

</style>
