// reactjs-tutorial/src/App.jsx
import Layout from './components/layouts/Layout'
import Hero from './components/Hero'
import Clocks from './components/Clocks'
import Calendar from './components/Calendar'
import Summary from './components/Summary'

function App() {


  return (
    <Layout>
      <Hero />
      <Clocks />
      <Calendar />
      <Summary />
    </Layout>
  )
}

export default App

// vue-tutorial/src/App.vue
<script setup>
  import Layout from './components/layouts/Layout.vue'
  import Hero from './components/Hero.vue'
  import Clocks from './components/Clocks.vue'
  import Calendar from './components/Calendar.vue'
  import Summary from './components/Summary.vue'

</script>

<template>
  <Layout>
    <Hero />
    <Clocks />
    <Calendar />
    <Summary />
  </Layout>
</template>

<style scoped>

</style>
