// svelte-tutorial/src/App.svelte
<script>
    import Calendar from "./lib/Calendar.svelte";
    import Clocks from "./lib/Clocks.svelte";
    import Hero from "./lib/Hero.svelte";
    import Layout from "./lib/layouts/Layout.svelte";
    import Summary from "./lib/Summary.svelte";


</script>

<Layout>
    {#snippet headache()}
        <Hero />
        <Clocks />
        <Calendar />
        <Summary />
    {/snippet}
</Layout>

// vue-tutorial/src/App.vue
<script setup>
  import Layout from './components/layouts/Layout.vue'
  import Hero from './components/Hero.vue'
  import Clocks from './components/Clocks.vue'
  import Calendar from './components/Calendar.vue'
  import Summary from './components/Summary.vue'

</script>

<template>
  <Layout>
    <Hero />
    <Clocks />
    <Calendar />
    <Summary />
  </Layout>
</template>

<style scoped>

</style>
