// vue-tutorial/src/components/Clocks.vue
<script setup>
    import { getTimePercentage } from '../utils'

    defineProps({
        data: Object
    })
    let snapshot = getTimePercentage()
    console.log(snapshot)
</script>

<template>
    <section id="clocks">
        <p><i>Time remaining in different units.</i></p>
        <div id="clocks-grid">
            <div class="card clock-card" v-for="(clock, clockIndex) in Object.keys(data)">
                <div class="circle" :style="{rotate: snapshot[clock] + 'deg'}">
                    <div class="ticker" :class="{[clock]: true}"></div>
                </div>
                <div>
                    <h5>{{ data[clock] }}</h5>
                </div>
            </div>
        </div>
    </section>
</template>

<style scoped>

</style>

// svelte-tutorial/src/lib/Clocks.svelte
<script>
    import { getTimePercentage } from "../utils";

    let { data } = $props();
    let snapshot = getTimePercentage()
</script>

<section id='clocks'>
    <p><i>Time remaining in different units.</i></p>
    <div class='clocks-grid'>
        {#each Object.keys(data) as clock, clockIndex}
        <div class='card clock-card'>
            <div class='circle' style:rotate="{snapshot[clock]}deg">
                <div class='ticker {clock}'></div>
            </div>
            <div>
                <h5>{data[clock]}</h5>
                <p>{clock}</p>
            </div>
        </div>
        {/each}
    </div>
</section>
