// vue-tutorial/src/components/Form.vue
<script setup>
    import { ref } from 'vue'

    const { handleCloseModal, handleUpdateData } = defineProps({
        handleCloseModal: Function,
        handleUpdateData: Function
    })

    const name = ref('')

    const currYear = new Date().getFullYear()
    const day = ref(1)
    const month = ref(1)
    const year = ref(currYear)

    const lifeExpectancy = ref(80)

    // Options
    const days = Array.from({ length: 31 }, (_, i) => i + 1)
    const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ]
    const years = Array.from({ length: 100 }, (_, i) => currYear - i)

    function handleSave() {
        handleUpdateData(name.value, `${year.value}-${month.value}-${day.value}`, lifeExpectancy.value)
    }
</script>

<template>
    <section id="form">
        <div>
            <h4 class="text-gradient">Your Details</h4>
            <button @click="handleCloseModal" class="link-button">
                <i class="fa-solid fa-xmark"></i>
            </button>
        </div>
        <div>
            <label for="name">Name</label>
            <input v-model="name" type="text" id="name" required />
        </div>
        <div>
            <div>
                Birthday
            </div>
            <div class="bday">
                <select v-model="day">
                    <option v-for="d in days" :key="d" :value="d">
                        {{ d }}
                    </option>
                </select>
                <select v-model="month">
                    <option v-for="(m, index) in months" :key="index" :value="index + 1">
                        {{ m }}
                    </option>
                </select>
                <select v-model="year">
                    <option v-for="y in years" :key="y" :value="y">
                        {{ y }}
                    </option>
                </select>
            </div>
        </div>
        <div>
            <label for="lifeExpectancy">Life Expectancy (years)</label>
            <input id="lifeExpectancy" type="number" max="120" required v-model="lifeExpectancy" />
        </div>

        <button @click="handleSave">Save</button>
    </section>
</template>

<style scoped>

</style>

// svelte-tutorial/src/lib/Form.svelte
<script>
    let { handleUpdateData, handleCloseModal } = $props();

    let name = $state("")

    let currYear = new Date().getFullYear()
    let day = $state(1)
    let month = $state(1)
    let year = $state(currYear)

    let lifeExpectancy = $state(80)

    // Generate numeric options
    const days = Array.from({ length: 31 }, (_, i) => i + 1);
    const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ];
    const years = Array.from({ length: 100 }, (_, i) => currYear - i);
</script>


<section id="form">
    <div>
        <h4 class="text-gradient">Your Details</h4>
        <button aria-label="button" class="link-button" onclick={handleCloseModal}>
            <i class="fa-solid fa-xmark"></i>
        </button>
    </div>
    <div>
        <label for="name">Name</label>
        <input bind:value={name} type="text" id="name" required />
    </div>
    <div>
        <div>Birthday</div>
        <div class="bday">
            <select bind:value={day}>
                {#each days as day}
                    <option value={day}>{day}</option>
                {/each}
            </select>
            <select bind:value={month}>
                {#each months as month, monthIndex}
                    <option value={monthIndex + 1}>{month}</option>
                {/each}
            </select>
            <select bind:value={year}>
                {#each years as year}
                    <option value={year}>{year}</option>
                {/each}
            </select>
        </div>
    </div>
    <div>
        <label for="lifeExpectancy">Life Expectancy (years)</label>
        <input type="number" required max={120} id="lifeExpectancy" bind:value={lifeExpectancy} />
    </div>
    <button onclick={() => {handleUpdateData(name, `${year}-${month}-${day}`, lifeExpectancy)}}>Save</button>
</section>
